//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05_EFBasic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsInfo
    {
        public int nid { get; set; }
        public string nTitle { get; set; }
        public int nTid { get; set; }
    
        public virtual NewsType NewsType { get; set; }
    }
}
