//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05_EFBasic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsType
    {
        public int tid { get; set; }
        public string tTitle { get; set; }
    
        public virtual NewsInfo NewsInfo { get; set; }
    }
}
