//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03_EFModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAddresses
    {
        public int StudentId { get; set; }
        public string Address { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
